In [1]:
# Load the dataset
import pandas as pd 
df=pd.read_csv(r"C:\Users\prave\OneDrive\Desktop\food-delievery\data\food_delievery.csv")
df.head()

,Restaurant ID,Restaurant name,Subzone,City,Order ID,Order Placed At,Order Status,Delivery,Distance,Items in order,...,Rating,Review,Cancellation / Rejection reason,Restaurant compensation (Cancellation),Restaurant penalty (Rejection),KPT duration (minutes),Rider wait time (minutes),Order Ready Marked,Customer complaint tag,Customer ID
0,20320607,Swaad,Sector 4,Delhi NCR,6168884918,"11:38 PM, September 10 2024",Delivered,Zomato Delivery,3km,"1 x Grilled Chicken Jamaican Tender, 1 x Grill...",...,NaN,NaN,NaN,NaN,NaN,18.35,11.6,Correctly,NaN,5d6c2b96db963098bc69768bea504c8bf46106a8a5178e...
1,20320607,Swaad,Sector 4,Delhi NCR,6170707559,"11:34 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Fries, 1 x Fried Chicken Angara ...",...,NaN,NaN,NaN,NaN,NaN,16.95,3.6,Correctly,NaN,0781815deb4a10a574e9fee4fa0b86b074d4a0b36175d5...
2,20320607,Swaad,Sector 4,Delhi NCR,6169375019,"03:52 PM, September 10 2024",Delivered,Zomato Delivery,<1km,1 x Bone in Peri Peri Grilled Chicken,...,NaN,NaN,NaN,NaN,NaN,14.05,12.2,Correctly,NaN,f93362f5ce5382657482d164e368186bcec9c6225fd93d...
3,20320607,Swaad,Sector 4,Delhi NCR,6151677434,"03:45 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Fried Chicken Ghostbuster Tender, 1 x Anga...",...,4.0,NaN,NaN,NaN,NaN,19.00,3.3,Correctly,NaN,1ed226d1b8a5f7acee12fc1d6676558330a3b2b742af5d...
4,20320607,Swaad,Sector 4,Delhi NCR,6167540897,"03:04 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Krispers, 1 x Fried Chicken Anga...",...,NaN,NaN,NaN,NaN,NaN,15.97,1.0,Correctly,NaN,d21a2ac6ea06b31cc3288ab20c4ef2f292066c096f2c5f...

In [2]:
# Shape
print(f"columns: {df.shape[0]}, rows: {df.shape[1]}")
df.duplicated().sum()
df.isnull().sum()

columns: 21321, rows: 29

Restaurant ID                                             0
Restaurant name                                           0
Subzone                                                   0
City                                                      0
Order ID                                                  0
Order Placed At                                           0
Order Status                                              0
Delivery                                                  0
Distance                                                  0
Items in order                                            0
Instructions                                          20601
Discount construct                                     5498
Bill subtotal                                             0
Packaging charges                                         0
Restaurant discount (Promo)                               0
Restaurant discount (Flat offs, Freebies & others)        0
Gold discount                                             0
Brand pack discount                                       0
Total                                                     0
Rating                                                18830
Review                                                21025
Cancellation / Rejection reason                       21135
Restaurant compensation (Cancellation)                21188
Restaurant penalty (Rejection)                        21318
KPT duration (minutes)                                  295
Rider wait time (minutes)                               168
Order Ready Marked                                        0
Customer complaint tag                                20852
Customer ID                                               0
dtype: int64

In [3]:
df["Order Status"].value_counts()

Order Status
Delivered           21131
Rejected              158
Returned               25
Return cancelled        3
Picked up               3
Timed out               1
Name: count, dtype: int64

In [4]:
print("Customers:", df["Customer ID"].nunique())
print("Restaurants:", df["Restaurant ID"].nunique())
print("Cities:", df["City"].nunique())

Customers: 11607
Restaurants: 21
Cities: 1

In [5]:
df["Discount construct"].value_counts()

Discount construct
50% off upto Rs.100       3561
Flat 15% off              1489
Flat Rs.200 off           1116
60% off upto Rs.120       1102
Flat Rs.150 off            816
                          ...
Buy 1 Get 1 - ₹637.00        1
Buy 1 Get 1 - ₹1306.00       1
Buy 1 Get 1 - ₹1487.00       1
Buy 1 Get 1 - ₹765.00        1
Flat Rs.760 off              1
Name: count, Length: 527, dtype: int64

In [6]:
df_clean=df.copy()
df_clean.head()

,Restaurant ID,Restaurant name,Subzone,City,Order ID,Order Placed At,Order Status,Delivery,Distance,Items in order,...,Rating,Review,Cancellation / Rejection reason,Restaurant compensation (Cancellation),Restaurant penalty (Rejection),KPT duration (minutes),Rider wait time (minutes),Order Ready Marked,Customer complaint tag,Customer ID
0,20320607,Swaad,Sector 4,Delhi NCR,6168884918,"11:38 PM, September 10 2024",Delivered,Zomato Delivery,3km,"1 x Grilled Chicken Jamaican Tender, 1 x Grill...",...,NaN,NaN,NaN,NaN,NaN,18.35,11.6,Correctly,NaN,5d6c2b96db963098bc69768bea504c8bf46106a8a5178e...
1,20320607,Swaad,Sector 4,Delhi NCR,6170707559,"11:34 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Fries, 1 x Fried Chicken Angara ...",...,NaN,NaN,NaN,NaN,NaN,16.95,3.6,Correctly,NaN,0781815deb4a10a574e9fee4fa0b86b074d4a0b36175d5...
2,20320607,Swaad,Sector 4,Delhi NCR,6169375019,"03:52 PM, September 10 2024",Delivered,Zomato Delivery,<1km,1 x Bone in Peri Peri Grilled Chicken,...,NaN,NaN,NaN,NaN,NaN,14.05,12.2,Correctly,NaN,f93362f5ce5382657482d164e368186bcec9c6225fd93d...
3,20320607,Swaad,Sector 4,Delhi NCR,6151677434,"03:45 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Fried Chicken Ghostbuster Tender, 1 x Anga...",...,4.0,NaN,NaN,NaN,NaN,19.00,3.3,Correctly,NaN,1ed226d1b8a5f7acee12fc1d6676558330a3b2b742af5d...
4,20320607,Swaad,Sector 4,Delhi NCR,6167540897,"03:04 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Krispers, 1 x Fried Chicken Anga...",...,NaN,NaN,NaN,NaN,NaN,15.97,1.0,Correctly,NaN,d21a2ac6ea06b31cc3288ab20c4ef2f292066c096f2c5f...

In [7]:
# Data Cleaning 
df_clean.columns=(
    df_clean.columns.str.lower().str.strip().str.replace(" ","_").str.replace("/","_").str.replace("(","").str.replace(")","")
)

In [8]:
df_clean.isnull().sum()

restaurant_id                                           0
restaurant_name                                         0
subzone                                                 0
city                                                    0
order_id                                                0
order_placed_at                                         0
order_status                                            0
delivery                                                0
distance                                                0
items_in_order                                          0
instructions                                        20601
discount_construct                                   5498
bill_subtotal                                           0
packaging_charges                                       0
restaurant_discount_promo                               0
restaurant_discount_flat_offs,_freebies_&_others        0
gold_discount                                           0
brand_pack_discount                                     0
total                                                   0
rating                                              18830
review                                              21025
cancellation___rejection_reason                     21135
restaurant_compensation_cancellation                21188
restaurant_penalty_rejection                        21318
kpt_duration_minutes                                  295
rider_wait_time_minutes                               168
order_ready_marked                                      0
customer_complaint_tag                              20852
customer_id                                             0
dtype: int64

In [9]:
# convert data columns 
df_clean['order_placed_at'].value_counts
df_clean["order_placed_at"] = pd.to_datetime(df_clean["order_placed_at"],errors="coerce")

C:\Users\prave\AppData\Local\Temp\ipykernel_18700\3335863517.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_clean["order_placed_at"] = pd.to_datetime(df_clean["order_placed_at"],errors="coerce")

In [10]:
#  Create Date Features
df_clean['order_placed_at'].value_counts
df_clean["hour"] = df_clean["order_placed_at"].dt.hour
df_clean["day"] = df_clean["order_placed_at"].dt.day
df_clean["year"] = df_clean["order_placed_at"].dt.year
df_clean["month"] = df_clean["order_placed_at"].dt.month

df_clean["month_name"] = df_clean["order_placed_at"].dt.month_name()
df_clean["day_name"]=df_clean["order_placed_at"].dt.day_name()

df_clean.columns.tolist()
df_clean.shape[1]

35

In [11]:
# Further Data Cleaning
df_clean["instructions"]=df_clean["instructions"].fillna("No Instructions")
df_clean["review"] = df_clean["review"].fillna("No Review")
df_clean["customer_complaint_tag"] = (df_clean["customer_complaint_tag"].fillna("No Complaint"))
df_clean["cancellation___rejection_reason"] = (df_clean["cancellation___rejection_reason"].fillna("No Cancellation"))
df_clean["discount_construct"] = (df_clean["discount_construct"].fillna("No Discount"))

In [12]:
df_clean.dtypes
# Only Distance need to be converted to Numeric 
df_clean['distance']=df_clean["distance"].str.replace("km","").str.replace("<1","0.6")
df_clean['distance']=pd.to_numeric(df_clean['distance'])

In [13]:
df_clean['distance'].dtype

dtype('float64')

In [14]:
# Handle Missing Operational Values

df_clean["kpt_duration_minutes"] = df_clean["kpt_duration_minutes"].fillna(df_clean["kpt_duration_minutes"].median())

df_clean["rider_wait_time_minutes"] = df_clean["rider_wait_time_minutes"].fillna(df_clean["rider_wait_time_minutes"].median())

In [15]:
df_clean.head()

,restaurant_id,restaurant_name,subzone,city,order_id,order_placed_at,order_status,delivery,distance,items_in_order,...,rider_wait_time_minutes,order_ready_marked,customer_complaint_tag,customer_id,hour,day,year,month,month_name,day_name
0,20320607,Swaad,Sector 4,Delhi NCR,6168884918,2024-09-10 23:38:00,Delivered,Zomato Delivery,3.0,"1 x Grilled Chicken Jamaican Tender, 1 x Grill...",...,11.6,Correctly,No Complaint,5d6c2b96db963098bc69768bea504c8bf46106a8a5178e...,23,10,2024,9,September,Tuesday
1,20320607,Swaad,Sector 4,Delhi NCR,6170707559,2024-09-10 23:34:00,Delivered,Zomato Delivery,2.0,"1 x Peri Peri Fries, 1 x Fried Chicken Angara ...",...,3.6,Correctly,No Complaint,0781815deb4a10a574e9fee4fa0b86b074d4a0b36175d5...,23,10,2024,9,September,Tuesday
2,20320607,Swaad,Sector 4,Delhi NCR,6169375019,2024-09-10 15:52:00,Delivered,Zomato Delivery,0.6,1 x Bone in Peri Peri Grilled Chicken,...,12.2,Correctly,No Complaint,f93362f5ce5382657482d164e368186bcec9c6225fd93d...,15,10,2024,9,September,Tuesday
3,20320607,Swaad,Sector 4,Delhi NCR,6151677434,2024-09-10 15:45:00,Delivered,Zomato Delivery,2.0,"1 x Fried Chicken Ghostbuster Tender, 1 x Anga...",...,3.3,Correctly,No Complaint,1ed226d1b8a5f7acee12fc1d6676558330a3b2b742af5d...,15,10,2024,9,September,Tuesday
4,20320607,Swaad,Sector 4,Delhi NCR,6167540897,2024-09-10 15:04:00,Delivered,Zomato Delivery,2.0,"1 x Peri Peri Krispers, 1 x Fried Chicken Anga...",...,1.0,Correctly,No Complaint,d21a2ac6ea06b31cc3288ab20c4ef2f292066c096f2c5f...,15,10,2024,9,September,Tuesday

In [16]:
# Strip Extra Spaces
text_cols = df_clean.select_dtypes(include='object').columns
for col in text_cols:
    df_clean[col] = df_clean[col].str.strip()

In [17]:
# Handling other NaN values
# Don't fill rating with 0. 
df_clean["restaurant_compensation_cancellation"] = (df_clean["restaurant_compensation_cancellation"].fillna(0))
df_clean["restaurant_penalty_rejection"] = (df_clean["restaurant_penalty_rejection"].fillna(0))

In [ ]:
# Final Code Validation 
print(df_clean.shape)
# Final Code Validation 
print(df_clean.shape)
print(df_clean.isnull().sum())
print(df_clean.dtypes)
print(df_clean.dtypes)

(21321, 35)
restaurant_id                                           0
restaurant_name                                         0
subzone                                                 0
city                                                    0
order_id                                                0
order_placed_at                                         0
order_status                                            0
delivery                                                0
distance                                                0
items_in_order                                          0
instructions                                            0
discount_construct                                      0
bill_subtotal                                           0
packaging_charges                                       0
restaurant_discount_promo                               0
restaurant_discount_flat_offs,_freebies_&_others        0
gold_discount                                           0
brand_pack_discount                                     0
total                                                   0
rating                                              18830
review                                                  0
cancellation___rejection_reason                         0
restaurant_compensation_cancellation                    0
restaurant_penalty_rejection                            0
kpt_duration_minutes                                    0
rider_wait_time_minutes                                 0
order_ready_marked                                      0
customer_complaint_tag                                  0
customer_id                                             0
hour                                                    0
day                                                     0
year                                                    0
month                                                   0
month_name                                              0
day_name                                                0
dtype: int64
restaurant_id                                                int64
restaurant_name                                             object
subzone                                                     object
city                                                        object
order_id                                                     int64
order_placed_at                                     datetime64[ns]
order_status                                                object
delivery                                                    object
distance                                                   float64
items_in_order                                              object
instructions                                                object
discount_construct                                          object
bill_subtotal                                              float64
packaging_charges                                          float64
restaurant_discount_promo                                  float64
restaurant_discount_flat_offs,_freebies_&_others           float64
gold_discount                                              float64
brand_pack_discount                                        float64
total                                                      float64
rating                                                     float64
review                                                      object
cancellation___rejection_reason                             object
restaurant_compensation_cancellation                       float64
restaurant_penalty_rejection                               float64
kpt_duration_minutes                                       float64
rider_wait_time_minutes                                    float64
order_ready_marked                                          object
customer_complaint_tag                                      object
customer_id                                                 object
hour                                                         int32
day                                                          int32
year                                                         int32
month                                                        int32
month_name                                                  object
day_name                                                    object
dtype: object

In [19]:
df_clean.shape

(21321, 35)

restaurant_id                                                int64
restaurant_name                                             object
subzone                                                     object
city                                                        object
order_id                                                     int64
order_placed_at                                     datetime64[ns]
order_status                                                object
delivery                                                    object
distance                                                   float64
items_in_order                                              object
instructions                                                object
discount_construct                                          object
bill_subtotal                                              float64
packaging_charges                                          float64
restaurant_discount_promo                                  float64
restaurant_discount_flat_offs,_freebies_&_others           float64
gold_discount                                              float64
brand_pack_discount                                        float64
total                                                      float64
rating                                                     float64
review                                                      object
cancellation___rejection_reason                             object
restaurant_compensation_cancellation                       float64
restaurant_penalty_rejection                               float64
kpt_duration_minutes                                       float64
rider_wait_time_minutes                                    float64
order_ready_marked                                          object
customer_complaint_tag                                      object
customer_id                                                 object
hour                                                         int32
day                                                          int32
year                                                         int32
month                                                        int32
month_name                                                  object
day_name                                                    object
dtype: object

In [27]:
df_clean.to_csv("../data/food_delievery_clean.csv")

In [ ]:
df_clean